services:
  - type: web
    name: pokemon-adventure-socket
    env: node
    plan: starter
    buildCommand: pnpm install --frozen-lockfile
    startCommand: node server/socket-server.js
    envVars:
      - key: SOCKET_SERVER_ORIGIN
        value: "https://pokemon-adventure-xaqx.vercel.app,https://localhost:3001,http://127.0.0.1:3001,http://localhost:3001"
      - key: SOCKET_SERVER_ORIGIN_REGEX
        value: "^https://pokemon-adventure-.*\\.vercel\\.app$"
